### ISSUE TITLE
jmap -heap <pid> command crashes

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/openjdk-runtime#80]
Some googling indicates that the `openjdk-debuginfo` package might be missing.

```
root@37d7e4efd82b:/# jmap -heap 1
Attaching to process ID 1, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 25.121-b13
using thread-local object allocation.
Garbage-First (G1) GC with 1 thread(s)
Heap Configuration:
   MinHeapFreeRatio         = 40
   MaxHeapFreeRatio         = 70
   MaxHeapSize              = 515899392 (492.0MB)
   NewSize                  = 1363144 (1.2999954223632812MB)
   MaxNewSize               = 309329920 (295.0MB)
   OldSize                  = 5452592 (5.1999969482421875MB)
   NewRatio                 = 2
   SurvivorRatio            = 8
   MetaspaceSize            = 21807104 (20.796875MB)
   CompressedClassSpaceSize = 1073741824 (1024.0MB)
   MaxMetaspaceSize         = 17592186044415 MB
   G1HeapRegionSize         = 1048576 (1.0MB)
Heap Usage:
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:
43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.tools.jmap.JMap.runTool(JMap.java:201)
        at sun.tools.jmap.JMap.main(JMap.java:130)
Caused by: java.lang.RuntimeException: unknown CollectedHeap type : class sun.jvm.hotspot.gc_
interface.CollectedHeap
        at sun.jvm.hotspot.tools.HeapSummary.run(HeapSummary.java:144)
        at sun.jvm.hotspot.tools.Tool.startInternal(Tool.java:260)
        at sun.jvm.hotspot.tools.Tool.start(Tool.java:223)
        at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
        at sun.jvm.hotspot.tools.HeapSummary.main(HeapSummary.java:49)
        ... 6 more
```

**Comment by meltsufin** [comment]
@joaoandremartins Can you look into this please? To reproduce:
1) deploy a Spring Boot app to flex
2) ssh into the instance
3) run "sudo docker exec -it gaeapp bash"
4) run "jmap -heap 1"

**Comment by joaoandremartins** [comment]
The problem with #83 is that the image size grows by 130MB just for a single dependency.

Instead, I suggest that jstat is used to get heap data (with -gc, -gccapacity, etc.), which doesn't require any extra dependency.

**Comment by meltsufin** [comment]
We can also turn on [native memory tracking](https://docs.oracle.com/javase/8/docs/technotes/guides/vm/nmt-8.html), which gives even more useful information about the JVM memory usage, such as off-heap memory.
I have tested this yet, however.

**Comment by meltsufin** [comment]
Closing because we decided against significantly expanding the image size by adding openjdk-8-dbg package.
